import { useEffect, useMemo, useRef, useState } from "react";
import { Link, useParams } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api, STAGES, type Plan, type Task } from "../api";
import { buildRelationGroups, blockedDeps, buildWorktreeFamilies, type RelationGroup, type BlockedDep } from "../relations";
import { ModelBubble } from "../components/ModelBubble";
import { GitHubBubble } from "../components/GitHubBubble";
import { WorktreeKanban } from "../components/WorktreeKanban";
import { WorktreeDetailPane } from "../components/WorktreeDetailPane";
import { SignalsPanel } from "../components/SignalsPanel";
import { MorningReportPanel } from "../components/MorningReportPanel";
import { IntakeReviewPanel } from "../components/IntakeReviewPanel";
import { rolesWithWriteTools, taskWriteCapability, type WriteCapability } from "../writeCapability";

type BoardTab = "intake" | "signals" | "report";

/** Small header pill summarizing this project's idle-window autonomy budget
 *  (PLANNING/overhaul/08 §3) — hidden entirely when autonomy isn't enabled. */
function AutonomyBudgetWidget({ projectId }: { projectId: number }) {
  const cfgQ = useQuery({
    queryKey: ["autonomy-config", projectId],
    queryFn: () => api.autonomyConfig(projectId),
    enabled: Number.isFinite(projectId),
  });
  const enabled = cfgQ.data?.config.enabled ?? false;
  const budgetQ = useQuery({
    queryKey: ["autonomy-budget", projectId],
    queryFn: () => api.autonomyBudget(projectId),
    enabled: Number.isFinite(projectId) && enabled,
    refetchInterval: 15_000,
  });
  if (!enabled || !budgetQ.data) return null;
  const b = budgetQ.data;
  return (
    <span
      className={`pill ${b.exhausted ? "warn" : "dim"}`}
      title={
        `Idle-window budget: ${b.consumed.taskStarts}/${b.budgets.maxTaskStarts} task starts, ` +
        `${b.consumed.execRuns}/${b.budgets.maxExecRuns} exec runs, ` +
        `${b.consumed.tokens.toLocaleString()}/${b.budgets.maxTokens.toLocaleString()} tokens`
      }
    >
      🤖 {b.exhausted ? "autonomy: budget exhausted" : "autonomy active"}
    </span>
  );
}

function planProgress(task: Task): string {
  if (!task.refinement_plan_json) return "not planned";
  try {
    const plan = JSON.parse(task.refinement_plan_json) as Plan;
    const done = plan.steps.filter((s) => s.status === "done").length;
    const current = plan.steps.find((s) => s.status === "pending");
    return `${done}/${plan.steps.length}${current ? ` · at ${current.role}` : ""}`;
  } catch {
    return "";
  }
}

function TaskCard({
  task,
  group,
  cap,
  isProcessing,
  blockedOn,
  isCleanupMode,
  isSelected,
  onToggleSelect,
}: {
  task: Task;
  group?: RelationGroup;
  cap: WriteCapability;
  isProcessing?: boolean;
  blockedOn?: BlockedDep[] | null;
  isCleanupMode?: boolean;
  isSelected?: boolean;
  onToggleSelect?: (taskId: string) => void;
}) {
  const isWontDo = task.exit_state === "wont_do";
  const watcherName = task.origin?.startsWith("watcher:") ? task.origin.slice("watcher:".length) : null;
  const watcherBadge = watcherName ? (
    <span className="pill dim" title={`Self-generated by the "${watcherName}" watcher`}>
      🤖 {watcherName}
    </span>
  ) : null;
  const degradedCount = task.degraded_runs ?? 0;
  const latestDegraded = task.latest_health === "degraded" || task.latest_health === "empty";
  const degradedChip =
    degradedCount > 0 ? (
      <span
        className={`pill ${latestDegraded ? "bad" : "warn"}`}
        title="Degraded/empty runs on this task — output may be salvaged or incomplete"
      >
        {degradedCount} degraded
      </span>
    ) : null;

  const className = [
    "card",
    isWontDo ? "card--wont-do" : "",
    isProcessing ? "card--processing" : "",
    latestDegraded && !isWontDo ? "card--degraded" : "",
    isCleanupMode ? "card--cleanup-mode" : "",
    isSelected ? "card--selected" : "",
  ]
    .filter(Boolean)
    .join("");

  if (isCleanupMode) {
    return (
      <div
        className={className}
        style={{ display: "block", color: "inherit", position: "relative", cursor: "pointer" }}
        onClick={() => onToggleSelect?.(task.task_id)}
      >
        {isSelected && <span className="card-checkmark" title="Selected for cleanup">✓</span>}
        <div className="title">{task.name ?? task.task_id.slice(0, 8)}</div>
        <div className="meta">
          {group && <span className="dot" style={{ background: group.color }} title="part of a related task family" />}
          <span className="pill dim">{task.intake_kind ?? task.level}</span>
          {watcherBadge}
          {cap === "acting" && <span className="pill accent">acting</span>}
          {cap === "planning" && <span className="pill dim">planning</span>}
          <span>{planProgress(task)}</span>
          {task.intake_review_state === "proposed" ? (
            <span className="pill human" title="Waiting on your review before a flow is chosen">needs review</span>
          ) : task.intake_review_state === "scouting" || task.intake_review_state === "skip_pending" ? (
            <span className="pill dim" title="Reading the repo to propose a flow">scouting</span>
          ) : task.paused === 1 ? (
            <span className="pill warn">paused</span>
          ) : null}
          {task.stale_reason && (
            <span className="pill bad" title={task.stale_reason}>
              possibly stale
            </span>
          )}
          {task.exit_state && (
            <span className={`pill ${isWontDo ? "dim" : task.exit_state === "ready_for_work" ? "ok" : "human"}`}>
              {task.exit_state.replace(/_/g, " ")}
            </span>
          )}
          {degradedChip}
          {blockedOn && blockedOn.length > 0 && (
            <span
              className="pill dim"
              title={`waiting on: ${blockedOn.map((d) => `${d.name ?? d.task_id.slice(0, 8)} (${d.stage})`).join(", ")}`}
            >
              blocked
            </span>
          )}
        </div>
      </div>
    );
  }

  return (
    <Link
      to="/tasks/$taskId"
      params={{ taskId: task.task_id }}
      className={className}
      style={{ display: "block", color: "inherit", position: "relative" }}
    >
      {group && group.rootId === task.task_id && <span className="card-root-star" title="Primary task">★</span>}
      <div className="title">{task.name ?? task.task_id.slice(0, 8)}</div>
      <div className="meta">
        {group && <span className="dot" style={{ background: group.color }} title="part of a related task family" />}
        <span className="pill dim">{task.intake_kind ?? task.level}</span>
        {cap === "acting" && <span className="pill accent">acting</span>}
        {cap === "planning" && <span className="pill dim">planning</span>}
        <span>{planProgress(task)}</span>
        {task.intake_review_state === "proposed" ? (
          <span className="pill human" title="Waiting on your review before a flow is chosen">needs review</span>
        ) : task.intake_review_state === "scouting" || task.intake_review_state === "skip_pending" ? (
          <span className="pill dim" title="Reading the repo to propose a flow">scouting</span>
        ) : task.paused === 1 ? (
          <span className="pill warn">paused</span>
        ) : null}
        {task.stale_reason && (
          <span className="pill bad" title={task.stale_reason}>
            possibly stale
          </span>
        )}
        {task.exit_state && (
          <span className={`pill ${isWontDo ? "dim" : task.exit_state === "ready_for_work" ? "ok" : "human"}`}>
            {task.exit_state.replace(/_/g, " ")}
          </span>
        )}
        {degradedChip}
        {blockedOn && blockedOn.length > 0 && (
          <span
            className="pill dim"
            title={`waiting on: ${blockedOn.map((d) => `${d.name ?? d.task_id.slice(0, 8)} (${d.stage})`).join(", ")}`}
          >
            blocked
          </span>
        )}
      </div>
    </Link>
  );
}

export function ProjectBoard() {
  const { projectId } = useParams({ strict: false }) as { projectId: string };
  const pid = Number(projectId);
  const qc = useQueryClient();
  const projectQ = useQuery({ queryKey: ["project", pid], queryFn: () => api.project(pid) });
  const tasksQ = useQuery({ queryKey: ["tasks", pid], queryFn: () => api.tasks(pid), refetchInterval: 3000 });
  const summaryQ = useQuery({ queryKey: ["summary"], queryFn: api.summary, refetchInterval: 10_000, staleTime: 5_000 });

  const [content, setContent] = useState("");
  const [name, setName] = useState("");
  const [kind, setKind] = useState("manual");

  // Cleanup mode state
  const [isCleanupMode, setIsCleanupMode] = useState(false);
  const [selectedTaskIds, setSelectedTaskIds] = useState<Set<string>>(new Set());
  const [showCleanupModal, setShowCleanupModal] = useState(false);
  // "Clean slate" — the select-all flavor of cleanup mode: instead of
  // archiving the selection as wont_do, it hard-deletes every selected task
  // (and its todos/decompositions) so the board comes back empty.
  const [isCleanSlate, setIsCleanSlate] = useState(false);

  // Intake review (PLANNING/intake-refinement.md): which task's proposal is
  // open, and whether this project reviews by default (which of the two intake
  // buttons is primary).
  const [reviewingTaskId, setReviewingTaskId] = useState<string | null>(null);
  const intakeReviewCfgQ = useQuery({
    queryKey: ["intake-review-config", pid],
    queryFn: () => api.intakeReviewConfig(pid),
    enabled: Number.isFinite(pid),
  });
  const reviewDefault = intakeReviewCfgQ.data?.config.default ?? "off";

  // Scheduler state for the intake column banner
  const [schedulerRunning, setSchedulerRunning] = useState(true);
  useEffect(() => {
    api.scheduler().then((s) => setSchedulerRunning(s.running)).catch(() => {});
    const iv = setInterval(() => {
      api.scheduler().then((s) => setSchedulerRunning(s.running)).catch(() => {});
    }, 5000);
    return () => clearInterval(iv);
  }, []);

  // `review` opts this one intake into the pre-flight review layer
  // (PLANNING/intake-refinement.md) instead of starting its filed kind's flow
  // immediately. Same endpoint, same task row — only the hold differs.
  const submit = useMutation({
    mutationFn: (review?: boolean) =>
      api.intake(pid, { name: name || "intake", content, intake_kind: kind, review }),
    onSuccess: (data) => {
      setContent("");
      setName("");
      qc.invalidateQueries({ queryKey: ["tasks", pid] });
      if (data.task_id) {
        console.log(`[intake] task ${data.task_id} created`);
        if (data.intake_review_state) setReviewingTaskId(data.task_id);
      }
    },
  });

  const bulkWontDo = useMutation({
    mutationFn: () => api.bulkWontDo(pid, [...selectedTaskIds]),
    onSuccess: () => {
      setSelectedTaskIds(new Set());
      setIsCleanupMode(false);
      setShowCleanupModal(false);
      qc.invalidateQueries({ queryKey: ["tasks", pid] });
    },
  });

  const bulkDelete = useMutation({
    mutationFn: () => api.bulkDelete(pid, [...selectedTaskIds]),
    onSuccess: () => {
      setSelectedTaskIds(new Set());
      setIsCleanupMode(false);
      setIsCleanSlate(false);
      setShowCleanupModal(false);
      qc.invalidateQueries({ queryKey: ["tasks", pid] });
    },
  });

  const byStage = (stage: string) => (tasksQ.data?.tasks ?? []).filter(
    (t) => (t.stage ?? "intake") === stage && t.exit_state !== "wont_do"
  );
  const archivedTasks = useMemo(
    () => (tasksQ.data?.tasks ?? []).filter((t) => t.exit_state === "wont_do"),
    [tasksQ.data]
  );
  const [showArchived, setShowArchived] = useState(false);

  // Self-generated tasks (PLANNING/overhaul/08 §2/§3). "Seen" is a server-side
  // flag (`tasks.seen_at`), so what counts as new is the same in every browser
  // and session — the first autonomy slice tracked this in localStorage, which
  // meant opening the board on a second machine re-flagged everything as new.
  const unglancedWatcherTasks = useMemo(
    () =>
      (tasksQ.data?.tasks ?? []).filter(
        (t) => (t.origin ?? "human").startsWith("watcher:") && !t.seen_at,
      ),
    [tasksQ.data],
  );
  const markSeen = useMutation({
    mutationFn: (taskIds: string[]) => api.markTasksSeen(taskIds),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["tasks", pid] }),
  });
  function markGlanced(taskId: string) {
    markSeen.mutate([taskId]);
  }
  function markAllGlanced() {
    const ids = unglancedWatcherTasks.map((t) => t.task_id);
    if (ids.length) markSeen.mutate(ids);
  }

  // Signals tab (PLANNING/overhaul/08)
  const autonomyConfigQ = useQuery({
    queryKey: ["autonomy-config", pid],
    queryFn: () => api.autonomyConfig(pid),
    enabled: Number.isFinite(pid),
  });
  const hasAnyWatcherTasks = useMemo(
    () => (tasksQ.data?.tasks ?? []).some((t) => (t.origin ?? "human").startsWith("watcher:")),
    [tasksQ.data],
  );
  const showSignalsTab = (autonomyConfigQ.data?.config.enabled ?? false) || hasAnyWatcherTasks;
  const openWatcherTasks = useMemo(
    () =>
      (tasksQ.data?.tasks ?? []).filter(
        (t) => (t.origin ?? "human").startsWith("watcher:") && t.stage !== "ready",
      ),
    [tasksQ.data],
  );
  const [activeTab, setActiveTab] = useState<BoardTab>("intake");
  const [tabTouched, setTabTouched] = useState(false);
  const prevOpenWatcherCount = useRef(0);
  useEffect(() => {
    const count = openWatcherTasks.length;
    if (!tabTouched && count > 0 && prevOpenWatcherCount.current === 0) {
      setActiveTab("signals");
    }
    prevOpenWatcherCount.current = count;
  }, [openWatcherTasks.length, tabTouched]);
  function selectTab(tab: BoardTab) {
    setActiveTab(tab);
    setTabTouched(true);
  }

  const relationGroups = useMemo(() => buildRelationGroups(tasksQ.data?.tasks ?? []), [tasksQ.data]);

  const worktreeFamilies = useMemo(() => buildWorktreeFamilies(tasksQ.data?.tasks ?? []), [tasksQ.data]);
  const activeWorktreeFamilies = useMemo(
    () => Array.from(worktreeFamilies.values()).filter((f) => f.root.git_worktree_path),
    [worktreeFamilies],
  );
  const [selectedFamilyRoot, setSelectedFamilyRoot] = useState<string | null>(null);
  const selectedFamily = selectedFamilyRoot ? worktreeFamilies.get(selectedFamilyRoot) : undefined;

  const harnessPolicyQ = useQuery({
    queryKey: ["harness-policy", pid],
    queryFn: () => api.harnessPolicy(pid),
    enabled: Number.isFinite(pid),
  });
  const capsByTaskId = useMemo(() => {
    const writeRoles = rolesWithWriteTools(projectQ.data?.roles ?? []);
    const allowWrite = harnessPolicyQ.data?.policy.allowWrite ?? false;
    const map = new Map<string, WriteCapability>();
    for (const t of tasksQ.data?.tasks ?? []) {
      map.set(t.task_id, taskWriteCapability(t, allowWrite, writeRoles));
    }
    return map;
  }, [tasksQ.data, projectQ.data?.roles, harnessPolicyQ.data?.policy.allowWrite]);

  const activeTaskIds = useMemo(() => new Set(summaryQ.data?.in_flight_task_ids ?? []), [summaryQ.data]);
  const tasksById = useMemo(() => new Map((tasksQ.data?.tasks ?? []).map((t) => [t.task_id, t])), [tasksQ.data]);
  const reviewList = useMemo(
    () => (summaryQ.data?.review_list ?? []).filter((r) => r.project_id === pid),
    [summaryQ.data, pid],
  );
  // Intakes parked on a human by the pre-flight review layer. Distinct from
  // `reviewList` above, which is tasks that reached stage:review after running
  // a whole flow — these haven't chosen a flow yet.
  const intakeReviewList = useMemo(
    () => (tasksQ.data?.tasks ?? []).filter((t) => t.intake_review_state === "proposed"),
    [tasksQ.data],
  );
  const reviewingTask = reviewingTaskId ? tasksById.get(reviewingTaskId) : undefined;

  function toggleCleanupMode() {
    if (isCleanupMode && selectedTaskIds.size > 0) {
      setShowCleanupModal(true);
    } else if (isCleanupMode) {
      setIsCleanupMode(false);
      setSelectedTaskIds(new Set());
      setIsCleanSlate(false);
    } else {
      setIsCleanupMode(true);
      setSelectedTaskIds(new Set());
      setIsCleanSlate(false);
    }
  }

  function toggleSelectTask(taskId: string) {
    setIsCleanSlate(false);
    setSelectedTaskIds((prev) => {
      const next = new Set(prev);
      if (next.has(taskId)) {
        next.delete(taskId);
      } else {
        next.add(taskId);
      }
      return next;
    });
  }

  function toggleCleanSlate() {
    if (isCleanSlate) {
      setIsCleanSlate(false);
      setSelectedTaskIds(new Set());
    } else {
      setIsCleanSlate(true);
      setSelectedTaskIds(new Set((tasksQ.data?.tasks ?? []).map((t) => t.task_id)));
    }
  }

  function handleCleanupConfirm() {
    if (isCleanSlate) {
      bulkDelete.mutate();
    } else {
      bulkWontDo.mutate();
    }
  }

  function handleCleanupCancel() {
    setShowCleanupModal(false);
  }

  function exitCleanupMode() {
    setIsCleanupMode(false);
    setSelectedTaskIds(new Set());
    setIsCleanSlate(false);
    setShowCleanupModal(false);
  }

  return (
    <div>
      <div className="row" style={{ marginBottom: 12 }}>
        <h2 style={{ margin: 0, color: "var(--brass)" }}>{projectQ.data?.project.name ?? "Project"}</h2>
        <span className="muted">{projectQ.data?.project.repo_path}</span>
        {projectQ.data && (
          <ModelBubble
            projectId={pid}
            defaultModel={projectQ.data.project.default_model}
            roles={projectQ.data.roles}
          />
        )}
        {projectQ.data && <GitHubBubble project={projectQ.data.project} />}
        <AutonomyBudgetWidget projectId={pid} />
        <div className="spacer" style={{ flex: 1 }} />
        <Link to="/projects/$projectId/roles" params={{ projectId }}>edit roles →</Link>
      </div>

      {intakeReviewList.length > 0 && (
        <div className="banner human" style={{ marginBottom: 12 }}>
          {intakeReviewList.length} intake
          {intakeReviewList.length === 1 ? "" : "s"} waiting on your review — nothing runs until you
          decide:{" "}
          {intakeReviewList.map((t, i) => (
            <span key={t.task_id}>
              {i > 0 && ", "}
              <button className="small" onClick={() => setReviewingTaskId(t.task_id)}>
                {t.name ?? t.task_id.slice(0, 8)}
              </button>
            </span>
          ))}
        </div>
      )}

      {reviewingTask && (
        <IntakeReviewPanel task={reviewingTask} onClose={() => setReviewingTaskId(null)} />
      )}

      {reviewList.length > 0 && (
        <div className="banner human" style={{ marginBottom: 12 }}>
          {reviewList.length} task{reviewList.length === 1 ? "" : "s"} need{reviewList.length === 1 ? "s" : ""} your review:{" "}
          {reviewList.map((r, i) => (
            <span key={r.task_id}>
              {i > 0 && ", "}
              <Link to="/tasks/$taskId" params={{ taskId: r.task_id }}>{r.name ?? r.task_id.slice(0, 8)}</Link>
            </span>
          ))}
        </div>
      )}

      <div className="panel">
        {showSignalsTab ? (
          <div className="tabs">
            <button className={`tab${activeTab === "intake" ? " active" : ""}`} onClick={() => selectTab("intake")}>
              New intake
            </button>
            <button className={`tab${activeTab === "signals" ? " active" : ""}`} onClick={() => selectTab("signals")}>
              🤖 Signals
              {unglancedWatcherTasks.length > 0 && (
                <span className="pill dim" style={{ marginLeft: 6 }}>
                  {unglancedWatcherTasks.length}
                </span>
              )}
            </button>
            <button className={`tab${activeTab === "report" ? " active" : ""}`} onClick={() => selectTab("report")}>
              ☀️ Report
            </button>
          </div>
        ) : (
          <h2>New intake</h2>
        )}

        {(!showSignalsTab || activeTab === "intake") && (
          <>
            <div className="grid-2">
              <div>
                <label>Name (optional)</label>
                <input value={name} onChange={(e) => setName(e.target.value)} placeholder="fix-login-bug" />
              </div>
              <div>
                <label>Kind</label>
                <select value={kind} onChange={(e) => setKind(e.target.value)}>
                  {["manual", "error_file", "feature", "bug", "chore", "spike", "research", "ux", "question"].map((k) => (
                    <option key={k} value={k}>{k}</option>
                  ))}
                </select>
              </div>
            </div>
            <label>Content — a request, a bare error/stack trace, or an open-ended research prompt</label>
            <textarea value={content} onChange={(e) => setContent(e.target.value)} placeholder="Consider how to address the UX issue on the settings page…" />
            <div className="row" style={{ marginTop: 8, gap: 8 }}>
              <button
                className={reviewDefault === "on" ? "" : "primary"}
                disabled={!content || submit.isPending}
                onClick={() => submit.mutate(false)}
              >
                {submit.isPending ? "Submitting…" : "Create task"}
              </button>
              <button
                className={reviewDefault === "on" ? "primary" : ""}
                disabled={!content || submit.isPending}
                onClick={() => submit.mutate(true)}
                title="Read the repo first, then propose the flow, roles and effort size for you to correct before anything runs"
              >
                Review intake ▸
              </button>
              <span className="muted">
                {reviewDefault === "on"
                  ? "This project reviews intakes by default."
                  : "The task appears in the intake column immediately."}
              </span>
            </div>
          </>
        )}

        {showSignalsTab && activeTab === "signals" && (
          <SignalsPanel
            projectId={pid}
            unglancedWatcherTasks={unglancedWatcherTasks}
            markGlanced={markGlanced}
            markAllGlanced={markAllGlanced}
          />
        )}

        {showSignalsTab && activeTab === "report" && <MorningReportPanel projectId={pid} />}
      </div>

      {selectedFamily ? (
        <div className="row" style={{ marginBottom: 12 }}>
          <span className="muted">
            {(tasksQ.data?.tasks ?? []).length} tasks · {activeWorktreeFamilies.length} active worktree
            {activeWorktreeFamilies.length === 1 ? "" : "s"}
          </span>
          <div className="spacer" style={{ flex: 1 }} />
          <button className="small" onClick={() => setSelectedFamilyRoot(null)}>
            Expand board ▾
          </button>
        </div>
      ) : (
        <>
          {isCleanupMode && (
            <div className="cleanup-banner" style={{ marginBottom: 12 }}>
              <span>
                {isCleanSlate
                  ? "🧹 Clean slate — every task selected for permanent deletion"
                  : "🗑️ Cleanup mode — click tasks to select them for archival"}
              </span>
              <div className="spacer" style={{ flex: 1 }} />
              <span className="muted" style={{ fontSize: 12, marginRight: 8 }}>
                {selectedTaskIds.size} selected
              </span>
              <button className="small" onClick={toggleCleanSlate} style={{ marginRight: 4 }}>
                {isCleanSlate ? "Deselect all" : "🧹 Select all (Clean slate)"}
              </button>
              <button className="small" onClick={exitCleanupMode} style={{ marginRight: 4 }}>
                Cancel
              </button>
              <button
                className={isCleanSlate ? "danger small" : "primary small"}
                disabled={selectedTaskIds.size === 0}
                onClick={() => setShowCleanupModal(true)}
              >
                {isCleanSlate
                  ? `Wipe everything (${selectedTaskIds.size})`
                  : `Archive selected (${selectedTaskIds.size})`}
              </button>
            </div>
          )}

          <div className="row" style={{ marginBottom: 8, justifyContent: "space-between" }}>
            <div className="row">
              <h3 style={{ margin: 0, color: "var(--ink-dim)", fontSize: 12, textTransform: "uppercase", letterSpacing: 1 }}>
                Kanban
              </h3>
            </div>
            <button
              className={`trash-icon${isCleanupMode ? " trash-icon--active" : ""}`}
              onClick={toggleCleanupMode}
              title={isCleanupMode ? "Confirm selection to archive" : "Enter cleanup mode to archive tasks"}
            >
              🗑️
            </button>
          </div>

          <div className="kanban">
            {STAGES.map((stage) => (
              <div className="col" key={stage}>
                <h3>
                  {stage} ({byStage(stage).length})
                  {stage === "intake" && !schedulerRunning && (
                    <span className="banner stopped" style={{ display: "block", marginTop: 4, fontSize: 12, fontWeight: 400, color: "var(--brass)" }}>
                      ⏸ Stopped
                    </span>
                  )}
                </h3>
                <div className="cards">
                  {byStage(stage).map((t) => {
                    const group = relationGroups.get(t.task_id);
                    return (
                      <TaskCard
                        key={t.task_id}
                        task={t}
                        group={group}
                        cap={capsByTaskId.get(t.task_id) ?? "pending"}
                        isProcessing={activeTaskIds.has(t.task_id)}
                        blockedOn={blockedDeps(t, tasksById)}
                        isCleanupMode={isCleanupMode}
                        isSelected={selectedTaskIds.has(t.task_id)}
                        onToggleSelect={toggleSelectTask}
                      />
                    );
                  })}
                </div>
              </div>
            ))}
          </div>

          {archivedTasks.length > 0 && (
            <div className="archived-panel" style={{ marginTop: 16 }}>
              <div
                className="archived-header"
                onClick={() => setShowArchived((v) => !v)}
              >
                <span className="archived-caret">{showArchived ? "▾" : "▸"}</span>
                <span>🗄️ Archived ({archivedTasks.length})</span>
                <span className="muted" style={{ fontSize: 11, marginLeft: 8 }}>
                  {showArchived ? "click to collapse" : "click to expand"}
                </span>
              </div>
              {showArchived && (
                <div className="archived-cards">
                  {archivedTasks.map((t) => (
                    <div key={t.task_id} className="card card--wont-do" style={{ cursor: "default" }}>
                      <div className="title">{t.name ?? t.task_id.slice(0, 8)}</div>
                      <div className="meta">
                        {t.intake_kind && <span className="pill dim">{t.intake_kind}</span>}
                        <span className="pill dim">{t.stage}</span>
                        {t.created_at && <span>{t.created_at.slice(0, 10)}</span>}
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}

          <TaskListTable
            tasks={tasksQ.data?.tasks ?? []}
            relationGroups={relationGroups}
            capsByTaskId={capsByTaskId}
            activeTaskIds={activeTaskIds}
            tasksById={tasksById}
            isCleanupMode={isCleanupMode}
            selectedTaskIds={selectedTaskIds}
            onToggleSelect={toggleSelectTask}
          />

          <WorktreeKanban
            families={activeWorktreeFamilies}
            activeTaskIds={activeTaskIds}
            onSelect={setSelectedFamilyRoot}
          />
        </>
      )}

      {selectedFamily && (
        <WorktreeDetailPane
          family={selectedFamily}
          onBack={() => setSelectedFamilyRoot(null)}
          onMutate={() => qc.invalidateQueries({ queryKey: ["tasks", pid] })}
        />
      )}

      {showCleanupModal && (
        <div className="modal-overlay">
          <div className="modal">
            {isCleanSlate ? (
              <>
                <h3>🧹 Clean slate</h3>
                <p style={{ color: "var(--ink-dim)", fontSize: 13, marginTop: 8 }}>
                  Permanently delete <strong>all {selectedTaskIds.size}</strong> task
                  {selectedTaskIds.size === 1 ? "" : "s"} in this project — including their todos, plans, and
                  decompositions? This cannot be undone.
                </p>
              </>
            ) : (
              <>
                <h3>🗑️ Archive tasks</h3>
                <p style={{ color: "var(--ink-dim)", fontSize: 13, marginTop: 8 }}>
                  Mark <strong>{selectedTaskIds.size}</strong> selected task{selectedTaskIds.size === 1 ? "" : "s"} as
                  "won't do" and archive them? They will be paused and removed from active scheduling.
                </p>
              </>
            )}
            <div className="modal-actions">
              <button onClick={handleCleanupCancel}>
                Cancel
              </button>
              <button
                className="danger"
                disabled={bulkWontDo.isPending || bulkDelete.isPending}
                onClick={handleCleanupConfirm}
              >
                {isCleanSlate
                  ? bulkDelete.isPending
                    ? "Wiping…"
                    : `Yes, permanently delete ${selectedTaskIds.size} task${selectedTaskIds.size === 1 ? "" : "s"}`
                  : bulkWontDo.isPending
                    ? "Archiving…"
                    : `Yes, archive ${selectedTaskIds.size} task${selectedTaskIds.size === 1 ? "" : "s"}`}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

const ALL = "all";
type TableSort = { col: string; dir: "asc" | "desc" };

function distinct(values: (string | null)[]): string[] {
  return Array.from(new Set(values.filter((v): v is string => !!v))).sort();
}

function TaskListTable({
  tasks,
  relationGroups,
  capsByTaskId,
  activeTaskIds,
  tasksById,
  isCleanupMode,
  selectedTaskIds,
  onToggleSelect,
}: {
  tasks: Task[];
  relationGroups: Map<string, RelationGroup>;
  capsByTaskId: Map<string, WriteCapability>;
  activeTaskIds: Set<string>;
  tasksById: Map<string, Task>;
  isCleanupMode?: boolean;
  selectedTaskIds?: Set<string>;
  onToggleSelect?: (taskId: string) => void;
}) {
  const [search, setSearch] = useState("");
  const [stageFilter, setStageFilter] = useState(ALL);
  const [levelFilter, setLevelFilter] = useState(ALL);
  const [kindFilter, setKindFilter] = useState(ALL);
  const [exitStateFilter, setExitStateFilter] = useState(ALL);
  const [sort, setSort] = useState<TableSort>({ col: "created_at", dir: "desc" });

  const stages = useMemo(() => distinct(tasks.map((t) => t.stage)), [tasks]);
  const levels = useMemo(() => distinct(tasks.map((t) => t.level)), [tasks]);
  const kinds = useMemo(() => distinct(tasks.map((t) => t.intake_kind)), [tasks]);
  const exitStates = useMemo(() => distinct(tasks.map((t) => t.exit_state)), [tasks]);

  const rows = useMemo(() => {
    const q = search.trim().toLowerCase();
    const filtered = tasks.filter((t) => {
      if (stageFilter !== ALL && t.stage !== stageFilter) return false;
      if (levelFilter !== ALL && t.level !== levelFilter) return false;
      if (kindFilter !== ALL && t.intake_kind !== kindFilter) return false;
      if (exitStateFilter !== ALL && t.exit_state !== exitStateFilter) return false;
      if (q && !(t.name ?? "").toLowerCase().includes(q) && !(t.content ?? "").toLowerCase().includes(q)) return false;
      return true;
    });
    const sorted = [...filtered];
    sorted.sort((a, b) => {
      const av = (a as unknown as Record<string, unknown>)[sort.col];
      const bv = (b as unknown as Record<string, unknown>)[sort.col];
      const an = av == null ? "" : String(av);
      const bn = bv == null ? "" : String(bv);
      const cmp = an.localeCompare(bn);
      return sort.dir === "asc" ? cmp : -cmp;
    });
    return sorted;
  }, [tasks, search, stageFilter, levelFilter, kindFilter, exitStateFilter, sort]);

  const th = (col: string, label: string) => (
    <th
      style={{ cursor: "pointer", whiteSpace: "nowrap", userSelect: "none" }}
      onClick={() => setSort((prev) => ({
        col,
        dir: prev.col === col ? (prev.dir === "asc" ? "desc" : "asc") : "asc",
      }))}
    >
      {label}
      {sort.col === col ? (sort.dir === "asc" ? " ▲" : " ▼") : ""}
    </th>
  );

  const filterSelect = (value: string, onChange: (v: string) => void, options: string[], allLabel: string) => (
    <select value={value} onChange={(e) => onChange(e.target.value)} style={{ width: "auto" }}>
      <option value={ALL}>{allLabel}</option>
      {options.map((o) => <option key={o} value={o}>{o}</option>)}
    </select>
  );

  return (
    <div className="panel" style={{ marginTop: 16, overflowX: "auto" }}>
      <h2>All tasks ({rows.length})</h2>
      <div className="row" style={{ marginBottom: 10 }}>
        <input
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          placeholder="search name or content…"
          style={{ maxWidth: 240 }}
        />
        {filterSelect(stageFilter, setStageFilter, stages, "stage: all")}
        {filterSelect(levelFilter, setLevelFilter, levels, "level: all")}
        {filterSelect(kindFilter, setKindFilter, kinds, "kind: all")}
        {filterSelect(exitStateFilter, setExitStateFilter, exitStates, "exit state: all")}
      </div>
      <table className="stats-table">
        <thead>
          <tr>
            {isCleanupMode && <th style={{ width: 36 }}>Sel.</th>}
            {th("name", "Name")}
            {th("stage", "Stage")}
            {th("level", "Level")}
            {th("intake_kind", "Kind")}
            <th style={{ whiteSpace: "nowrap" }}>Mode</th>
            {th("exit_state", "Exit State")}
            <th style={{ whiteSpace: "nowrap" }}>Blocked</th>
            {th("created_at", "Created")}
          </tr>
        </thead>
        <tbody>
          {rows.map((t) => {
            const group = relationGroups.get(t.task_id);
            const blocked = blockedDeps(t, tasksById);
            return (
              <tr
                key={t.task_id}
                className={[
                  activeTaskIds.has(t.task_id) ? "row--processing" : "",
                  isCleanupMode && selectedTaskIds?.has(t.task_id) ? "row--selected" : "",
                ].filter(Boolean).join(" ")}
                style={isCleanupMode ? { cursor: "pointer" } : undefined}
                onClick={isCleanupMode ? () => onToggleSelect?.(t.task_id) : undefined}
              >
                {isCleanupMode && (
                  <td>
                    <input
                      type="checkbox"
                      checked={selectedTaskIds?.has(t.task_id) ?? false}
                      onChange={() => onToggleSelect?.(t.task_id)}
                      onClick={(e) => e.stopPropagation()}
                    />
                  </td>
                )}
                <td>
                  <span className="dot" style={{ background: group ? group.color : "transparent", marginRight: 6 }} title={group ? "part of a related task family" : undefined} />
                  {isCleanupMode ? (
                    <span style={{ color: "var(--ink)" }}>{t.name ?? t.task_id.slice(0, 8)}</span>
                  ) : (
                    <Link to="/tasks/$taskId" params={{ taskId: t.task_id }}>{t.name ?? t.task_id.slice(0, 8)}</Link>
                  )}
                </td>
                <td>{t.stage ?? "—"}</td>
                <td>{t.level ?? "—"}</td>
                <td>{t.intake_kind ?? "—"}</td>
                <td>
                  {(() => {
                    const cap = capsByTaskId.get(t.task_id) ?? "pending";
                    if (cap === "acting") return <span className="pill accent">acting</span>;
                    if (cap === "planning") return <span className="pill dim">planning</span>;
                    return "—";
                  })()}
                </td>
                <td>{t.exit_state ?? "—"}</td>
                <td>
                  {blocked && blocked.length > 0 && (
                    <span
                      className="pill dim"
                      title={`waiting on: ${blocked.map((d) => `${d.name ?? d.task_id.slice(0, 8)} (${d.stage})`).join(", ")}`}
                    >
                      blocked
                    </span>
                  )}
                </td>
                <td>{t.created_at ?? "—"}</td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}